apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-store
  labels:
    app: entity-store
spec:
  replicas: 3
  selector:
    matchLabels:
      app: entity-store
  template:
    metadata:
      labels:
        app: entity-store
    spec:
      containers:
        - name: entity-store
          image: <YOUR_REGISTRY>/entity-store:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo:27017"
            - name: MONGODB_DB
              value: "entitiesdb"
            - name: MAX_POOL_SIZE
              value: "100"
            - name: LOG_LEVEL
              value: "INFO"
            - name: SERVICE_PORT
              value: "8000"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: entity-store
spec:
  selector:
    app: entity-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
