---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-saver-mongo
  labels:
    app: memory-saver-mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: memory-saver-mongo
  template:
    metadata:
      labels:
        app: memory-saver-mongo
    spec:
      containers:
        - name: memory-saver-mongo
          image: <YOUR_REGISTRY>/memory-saver-mongo:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: uri
            - name: DB_NAME
              value: "chatbot"
            - name: COLLECTION_NAME
              value: "state"
            - name: MONGO_MAX_POOL_SIZE
              value: "100"
            - name: MONGO_MIN_POOL_SIZE
              value: "0"
            - name: MONGO_SERVER_SELECTION_TIMEOUT_MS
              value: "5000"
            - name: APP_PORT
              value: "8000"
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: memory-saver-mongo
spec:
  selector:
    app: memory-saver-mongo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
