apiVersion: apps/v1
kind: Deployment
metadata:
  name: dialogue-manager
  labels:
    app: dialogue-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dialogue-manager
  template:
    metadata:
      labels:
        app: dialogue-manager
    spec:
      containers:
        - name: dialogue-manager
          image: <your-registry>/dialogue-manager:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: APP_HOST
              value: "0.0.0.0"
            - name: APP_PORT
              value: "8000"
            - name: LOG_LEVEL
              value: "INFO"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: uri
            - name: MONGO_MAX_POOL_SIZE
              value: "50"
            - name: SERVE_METRICS
              value: "true"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: dialogue-manager
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: dialogue-manager
