apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-client-microservice
  labels:
    app: http-client-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-client-microservice
  template:
    metadata:
      labels:
        app: http-client-microservice
    spec:
      containers:
        - name: http-client-microservice
          image: your-repo/http-client-microservice:latest
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: SERVICE_HOST
              value: "0.0.0.0"
            - name: SERVICE_PORT
              value: "8000"
            - name: LOG_LEVEL
              value: "INFO"
            - name: AIOHTTP_POOL_SIZE
              value: "100"
            - name: DEFAULT_TIMEOUT
              value: "30"
            # - name: DATABASE_URL
            #   valueFrom: { secretKeyRef: { name: db-secret, key: DATABASE_URL } }
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: http-client-microservice
spec:
  type: ClusterIP
  selector:
    app: http-client-microservice
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
