apiVersion: v1
kind: Namespace
metadata:
  name: ai-chatbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chatbot-utils
  namespace: ai-chatbot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-chatbot-utils
  template:
    metadata:
      labels:
        app: ai-chatbot-utils
    spec:
      containers:
        - name: ai-chatbot-utils
          image: your-registry/ai-chatbot-utils:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          env:
            - name: PORT
              value: "8000"
            - name: LOG_LEVEL
              value: "INFO"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: ai-chatbot-db-secret
                  key: DB_URL
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ai-chatbot-utils-svc
  namespace: ai-chatbot
spec:
  selector:
    app: ai-chatbot-utils
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
