apiVersion: apps/v1
kind: Deployment
metadata:
  name: intents-service
  labels:
    app: intents-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: intents-service
  template:
    metadata:
      labels:
        app: intents-service
    spec:
      containers:
        - name: intents-service
          image: <YOUR_REGISTRY>/intents-service:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: DB_URL
              value: "postgresql://user:pass@postgres:5432/intentsdb"
            - name: POOL_MIN
              value: "1"
            - name: POOL_MAX
              value: "10"
            - name: LOG_LEVEL
              value: "INFO"
            - name: METRICS_ENABLED
              value: "true"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: intents-service
spec:
  selector:
    app: intents-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
