apiVersion: apps/v1
kind: Deployment
metadata:
  name: intent-service
  labels:
    app: intent-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: intent-service
  template:
    metadata:
      labels:
        app: intent-service
    spec:
      containers:
        - name: intent-service
          image: your-registry/intent-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: intent-service-secrets
                  key: mongo_uri
            - name: DB_NAME
              value: "app_db"
            - name: MONGO_MAX_POOL_SIZE
              value: "50"
            - name: PORT
              value: "8000"
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: intent-service
spec:
  selector:
    app: intent-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
