apiVersion: apps/v1
kind: Deployment
metadata:
  name: dialogue-service
  labels:
    app: dialogue-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dialogue-service
  template:
    metadata:
      labels:
        app: dialogue-service
    spec:
      containers:
        - name: dialogue-service
          image: your-registry/dialogue-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: PORT
              value: "8000"
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: dialogue-db-secret
                  key: dsn
            - name: DB_POOL_MIN
              value: "1"
            - name: DB_POOL_MAX
              value: "10"
            - name: METRICS_ENABLED
              value: "true"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /rest/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /rest/readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: dialogue-service
spec:
  selector:
    app: dialogue-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
