apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-microservice
  labels:
    app: nlp-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nlp-microservice
  template:
    metadata:
      labels:
        app: nlp-microservice
    spec:
      containers:
        - name: nlp-microservice
          image: <YOUR_REGISTRY>/nlp-microservice:latest
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: "production"
            - name: DB_URL
              value: "postgresql+psycopg2://user:password@postgres:5432/dbname"
            - name: DB_POOL_SIZE
              value: "5"
            - name: DB_MAX_OVERFLOW
              value: "10"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: nlp-microservice
spec:
  selector:
    app: nlp-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
