apiVersion: apps/v1
kind: Deployment
metadata:
  name: bots-service
  labels:
    app: bots-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bots-service
  template:
    metadata:
      labels:
        app: bots-service
    spec:
      containers:
        - name: bots-service
          image: <your-registry>/bots-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: LOG_LEVEL
              value: "INFO"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bots-service-secrets
                  key: database_url
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: bots-service
spec:
  type: ClusterIP
  selector:
    app: bots-service
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
