apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-store-deployment
  labels:
    app: bot-store
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bot-store
  template:
    metadata:
      labels:
        app: bot-store
    spec:
      containers:
        - name: bot-store
          image: registry.example.com/bot-store:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DB_URL
              value: "mongodb://mongo:27017"
            - name: DB_NAME
              value: "mydb"
            - name: DB_MAX_POOL_SIZE
              value: "100"
            - name: DB_MIN_POOL_SIZE
              value: "0"
            - name: ENABLE_METRICS
              value: "false"
            - name: LOG_LEVEL
              value: "INFO"
            - name: APP_ENV
              value: "production"
            - name: PORT
              value: "8000"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1024Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: bot-store-service
spec:
  selector:
    app: bot-store
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
