apiVersion: v1
kind: Namespace
metadata:
  name: integrations
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integrations-deployment
  namespace: integrations
  labels:
    app: integrations
spec:
  replicas: 3
  selector:
    matchLabels:
      app: integrations
  template:
    metadata:
      labels:
        app: integrations
    spec:
      containers:
        - name: integrations
          image: <YOUR_REGISTRY>/integrations-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: APP_NAME
              value: "integrations-service"
            - name: ENV
              value: "production"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PORT
              value: "8000"
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: integrations-db-secret
                  key: DATABASE_URL
            - name: DB_MAX_POOL
              value: "10"
            - name: METRICS_ENABLED
              value: "true"
            - name: REQUIRE_DB_ON_STARTUP
              value: "false"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
      # Configure imagePullSecrets if using a private registry
      # imagePullSecrets:
      #   - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: integrations-service
  namespace: integrations
spec:
  selector:
    app: integrations
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
