apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatlogs-deployment
  labels:
    app: chatlogs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatlogs
  template:
    metadata:
      labels:
        app: chatlogs
    spec:
      containers:
        - name: chatlogs
          image: YOUR_REGISTRY/chatlogs:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: chatlogs-db-secret
                  key: DB_DSN
            - name: LOG_LEVEL
              value: "INFO"
            - name: WORKERS
              value: "2"
            - name: METRICS_PATH
              value: "/metrics"
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: chatlogs-service
spec:
  selector:
    app: chatlogs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
